package com.projectd.interpreter.syntax.tree;

public enum AstGrammarNodeType {
    PROGRAM,
    STATEMENT,
    ASSIGNMENT,
    DECLARATION,
    VARIABLE_DEFINITION,
    PRINT,
    RETURN,
    IF,
    LOOP,
    LOOP_BODY,
    BODY,
    PRIMARY,
    TAIL,
    EXPRESSION,
    CONJUNCTION,
    RELATION,
    FACTOR,
    TERM,
    UNARY,
    LITERAL,
    FUNCTION_LITERAL,
    PARAMETERS,
    FUN_BODY,
    ARRAY_LITERAL,
    TUPLE_LITERAL,
    TUPLE_ELEMENT,
    TYPE_INDICATOR;
}
